# Generated by Django 6.0.2 on 2026-02-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("purchase_link", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ingredients",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("cuisine", models.CharField(blank=True, max_length=100, null=True)),
                ("prep_time_mins", models.IntegerField(blank=True, null=True)),
                ("calories", models.IntegerField(null=True)),
                ("approval_status", models.CharField(default="pending", max_length=50)),
            ],
            options={
                "db_table": "recipes",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_required",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.recipe"
                    ),
                ),
            ],
            options={
                "db_table": "recipe_ingredients",
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="core.RecipeIngredient",
                to="core.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.recipe"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
            ],
            options={
                "db_table": "recipe_tags",
                "unique_together": {("recipe", "tag")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", through="core.RecipeTag", to="core.tag"
            ),
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("search_query", models.CharField(max_length=255)),
                ("searched_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "search_history",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_recipes",
                to="core.user",
            ),
        ),
        migrations.CreateModel(
            name="UserPantry",
            fields=[
                ("pantry_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry_items",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_pantry",
            },
        ),
    ]
